//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador : Utilizador
    {
        public string nome { get; set; }
        public int nInterno { get; set; }
        public string morada { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string cargo { get; set; }
    }
}
