//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exame
    {
        public Exame()
        {
            this.Utente = new HashSet<Utente>();
            this.Medico = new HashSet<Medico>();
        }
    
        public int Id { get; set; }
        public string especialidade { get; set; }
        public string preco { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual Rececionista Rececionista { get; set; }
        public virtual ICollection<Utente> Utente { get; set; }
        public virtual ICollection<Medico> Medico { get; set; }
    }
}
