//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicacao
    {
        public Medicacao()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int Id { get; set; }
        public string nomeMedicacao { get; set; }
        public string administracao { get; set; }
        public string preco { get; set; }
        public System.DateTime data { get; set; }
        public string dosagem { get; set; }
        public string comparticao { get; set; }
    
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}
