//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utente
    {
        public int Id { get; set; }
        public string primeiroNome { get; set; }
        public string apelido { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string morada { get; set; }
        public string codigoPostal { get; set; }
        public string email { get; set; }
        public string sexo { get; set; }
        public string contacto { get; set; }
        public string peso { get; set; }
        public string altura { get; set; }
        public string glicemia { get; set; }
        public string tensao { get; set; }
        public string colestrol { get; set; }
        public string saturacao { get; set; }
        public string batimentoCardiaco { get; set; }
    
        public virtual Exame Exame { get; set; }
        public virtual Consulta Consulta { get; set; }
    }
}
